### ISSUE TITLE
Initialise window.plausible() independent of the Neos context & package settings

### ISSUE THREAD

**Issue by jobee** [CarbonPackages/Carbon.Plausible#4]
To prevent yourself from checking `if (window.plausible)` each time you add some custom events via JS, it would be useful to render this line in every context & package settings (Development, Backend, etc.).
https://github.com/CarbonPackages/Carbon.Plausible/blob/c8baee0a1fafd035d8965fbaafdcc5c28d335059/Resources/Private/Fusion/Component/TrackingCode.fusion#L42

What do you think?

**Comment by jonnitto** [comment]
Hey Joachim,
Thank you for your feedback!

Good point.

First, you could set the following settings:

```yaml
Carbon:
  Plausible:
    enable: true
    default:
      customEvents: true
```

And I made some changed to `[Carbon.Plausible:Component.TrackingCode](Resources/Private/Fusion/Component/TrackingCode.fusion)`: 

You can override the Fusion, to always render the inline script tag:

```elm
prototype(Carbon.Plausible:Component.TrackingCode) {
    renderInlineScriptTag = true
}
```

What do you think about this solution? If it is ok for you, I will release a new version…

**Comment by jobee** [comment]
Hi Jon,

thanks for your quick response.
Setting `customEvents: true` & overriding the fusion prototype works for me. But I'm not sure if the latter is really necessary.

Whenever someone is using custom events the inline script should render or do I miss anything?

```
prototype(Carbon.Plausible:Component.TrackingCode) {
    ...
    renderInlineScriptTag = ${this.renderPlausibleScriptTag || this.customEvents}
    ...
}
```
